/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PracticaImagenes;

import sm.erc.iu.Lienzo2DImagen;

/**
 * Ventana interna que contiene un Lienzo2DImagen y el objeto VentanaPrincipal que la ha creado.
 * Gestiona evento de movimiento de ratón y activación de esta VentanaInternaImagen.
 * @verion 1.0
 * @author Elena Romero Contreras
 */
public class VentanaInternaImagen extends javax.swing.JInternalFrame{

    private VentanaPrincipal parent;
    
    /**
     * Crea nueva VentanaInternaImagen
     * @param p objeto VentanaPrincipal desde el que se ha llamado al constructor
     * de esta VentanaInternaImagen
     */
    public VentanaInternaImagen(VentanaPrincipal p) {
        initComponents();
        this.parent = p;
    }

    /**
     * Devuelve el Lienzo2DImagen que contiene esta VentanaInternaImagen
     * @return lienzo de esta ventana
     */
    public Lienzo2DImagen getLienzo(){
        return this.lienzo;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo = new sm.erc.iu.Lienzo2DImagen();

        setBackground(java.awt.Color.lightGray);
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo lienzo");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lienzo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lienzoMouseMoved(evt);
            }
        });

        javax.swing.GroupLayout lienzoLayout = new javax.swing.GroupLayout(lienzo);
        lienzo.setLayout(lienzoLayout);
        lienzoLayout.setHorizontalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );
        lienzoLayout.setVerticalGroup(
            lienzoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Gestiona evento que se produce al activar esta VentanaInterna.
     * Llama al método que resetea la VentanaPrincipal desde la que se le ha llamado
     * @param evt evento que se produce al activar la ventana
     */
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        parent.reset();
    }//GEN-LAST:event_formInternalFrameActivated

    /**
     * Gestiona evento que se produce al mover el ratón sobre el lienzo.
     * Llama al método del padre que muestra coordenada en la que se encuentra el ratón
     * @param evt evento que se produce al mover el ratón
     */
    private void lienzoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzoMouseMoved
        parent.setCoord(evt);
    }//GEN-LAST:event_lienzoMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.erc.iu.Lienzo2DImagen lienzo;
    // End of variables declaration//GEN-END:variables
}
