/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PracticaImagenes;

import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import java.awt.BorderLayout;

/**
 * Ventana interna que contiene una Webcam y muestra lo que está captando.
 * @verion 1.0
 * @author Elena Romero Contreras
 */
public class VentanaInternaCamara extends javax.swing.JInternalFrame {

    private Webcam camara = null;
    /**
     * Crea nueva VentanaInternaCamara
     */
    public VentanaInternaCamara() {
        initComponents();
        camara = Webcam.getDefault();
        if(camara!= null){
            WebcamPanel areaVisual = new WebcamPanel(camara);
            if(areaVisual != null){
                getContentPane().add(areaVisual, BorderLayout.CENTER);
                pack();
            }
        }
    }
    /**
     * Devuelve instancia de VentanaInternaCamara.
     * @return ventana interna con webcam si se ha creado sin errores,
     * false si no ha podido crearse
     */
    public static VentanaInternaCamara getInstance(){
        VentanaInternaCamara v = new VentanaInternaCamara();
        return (v.camara !=null?v:null);
    }
    
    /**
     * Devuelve la camara de esta VentanaInternaCamara
     * @return camara
     */
    public Webcam getCamera(){
        return camara;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
